---
name: 'Auto-Merge'
on:
  check_suite:
    types:
      - 'completed'
  pull_request:
    types:
      - 'labeled'
      - 'unlabeled'
      - 'opened'
      - 'edited'
      - 'reopened'
      - 'synchronize'
      - 'ready_for_review'
      - 'unlocked'
  pull_request_review:
    types:
      - 'submitted'
  status: {}
jobs:
  dependabot:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'pascalgn/automerge-action@v0.14.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'dependencies'
          MERGE_FILTER_AUTHOR: 'dependabot[bot]'
